# Generated by Django 6.0 on 2025-12-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verification_code',
            field=models.CharField(blank=True, help_text='Six-digit verification code sent to email.', max_length=6, null=True, verbose_name='email verification code'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when verification code was sent.', null=True, verbose_name='verification code sent at'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='Designates whether the user has verified their email address.', verbose_name='email verified'),
        ),
    ]
