# Generated by Django 6.0 on 2025-12-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that phoneNumber already exists.'}, max_length=20, null=True, unique=True, verbose_name='phoneNumber'),
        ),
    ]
