# Generated by Django 6.0 on 2025-12-11 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('orders', '0001_initial'),
        ('users', '0005_customuser_first_name_customuser_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyPointsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(help_text='Positive for addition, negative for deduction')),
                ('balance_after', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Loyalty Points History',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_confirmation', models.BooleanField(default=True)),
                ('order_shipped', models.BooleanField(default=True)),
                ('order_delivered', models.BooleanField(default=True)),
                ('order_cancelled', models.BooleanField(default=True)),
                ('payment_confirmation', models.BooleanField(default=True)),
                ('flash_sales', models.BooleanField(default=True)),
                ('daily_deals', models.BooleanField(default=True)),
                ('price_drop_alerts', models.BooleanField(default=False)),
                ('new_arrivals', models.BooleanField(default=True)),
                ('back_in_stock', models.BooleanField(default=True)),
                ('baby_care_tips', models.BooleanField(default=True)),
                ('security_alerts', models.BooleanField(default=True)),
                ('account_updates', models.BooleanField(default=True)),
                ('birthday_offers', models.BooleanField(default=True)),
                ('reviews_replies', models.BooleanField(default=True)),
                ('wishlist_reminders', models.BooleanField(default=True)),
                ('abandoned_cart_reminders', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Preferences',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=20)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('estate', models.CharField(blank=True, max_length=100)),
                ('building', models.CharField(blank=True, max_length=100)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('county', models.CharField(choices=[('nairobi', 'Nairobi'), ('mombasa', 'Mombasa'), ('kisumu', 'Kisumu'), ('nakuru', 'Nakuru'), ('eldoret', 'Eldoret'), ('thika', 'Thika'), ('nyeri', 'Nyeri'), ('kakamega', 'Kakamega'), ('kisii', 'Kisii'), ('meru', 'Meru'), ('machakos', 'Machakos'), ('kitale', 'Kitale'), ('kericho', 'Kericho'), ('bungoma', 'Bungoma'), ('malindi', 'Malindi'), ('lamu', 'Lamu'), ('garissa', 'Garissa'), ('wajir', 'Wajir'), ('mandera', 'Mandera'), ('marsabit', 'Marsabit'), ('isiolo', 'Isiolo'), ('kitui', 'Kitui'), ('embu', 'Embu'), ('busia', 'Busia'), ('siaya', 'Siaya'), ('homa_bay', 'Homa Bay'), ('migori', 'Migori'), ('kilifi', 'Kilifi'), ('taita_taveta', 'Taita Taveta'), ('tana_river', 'Tana River'), ('west_pokot', 'West Pokot'), ('samburu', 'Samburu'), ('trans_nzoia', 'Trans Nzoia'), ('uasin_gishu', 'Uasin Gishu'), ('elgeyo_marakwet', 'Elgeyo Marakwet'), ('nandi', 'Nandi'), ('baringo', 'Baringo'), ('laikipia', 'Laikipia'), ('nakuru', 'Nakuru'), ('narok', 'Narok'), ('kajiado', 'Kajiado'), ('kericho', 'Kericho'), ('bomet', 'Bomet'), ('kakamega', 'Kakamega'), ('vihiga', 'Vihiga'), ('bungoma', 'Bungoma'), ('busia', 'Busia'), ('siaya', 'Siaya'), ('kisumu', 'Kisumu'), ('homa_bay', 'Homa Bay'), ('migori', 'Migori'), ('kisii', 'Kisii'), ('nyamira', 'Nyamira'), ('nairobi', 'Nairobi'), ('kiambu', 'Kiambu'), ('muranga', "Murang'a"), ('nyandarua', 'Nyandarua'), ('nyeri', 'Nyeri'), ('kirinyaga', 'Kirinyaga'), ('meru', 'Meru'), ('tharaka_nithi', 'Tharaka Nithi'), ('embu', 'Embu'), ('kitui', 'Kitui'), ('machakos', 'Machakos'), ('makueni', 'Makueni')], default='nairobi', max_length=50)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('address_type', models.CharField(choices=[('home', 'Home (Family Residence)'), ('office', 'Office/Work'), ('grandparents', 'Grandparents House'), ('daycare', 'Daycare/Nursery'), ('relative', "Relative's House"), ('other', 'Other')], default='home', max_length=20)),
                ('is_default_shipping', models.BooleanField(default=False)),
                ('is_default_billing', models.BooleanField(default=False)),
                ('delivery_instructions', models.TextField(blank=True, help_text='Specific instructions for delivering baby clothes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'User Addresses',
                'ordering': ['-is_default_shipping', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='child_age_range',
            field=models.CharField(blank=True, choices=[('0-6m', '0-6 Months'), ('6-12m', '6-12 Months'), ('1-2y', '1-2 Years'), ('2-3y', '2-3 Years'), ('3-4y', '3-4 Years'), ('4-5y', '4-5 Years'), ('5-6y', '5-6 Years'), ('multiple', 'Multiple ages')], max_length=20, verbose_name='child age range'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='child_gender',
            field=models.CharField(blank=True, choices=[('boy', 'Boy'), ('girl', 'Girl'), ('both', 'Both'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, verbose_name='child gender'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='children_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of children the user has', verbose_name='number of children'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='email verified at'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='has_children',
            field=models.BooleanField(default=False, help_text='Does this user have children?', verbose_name='has children'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_phone_verified',
            field=models.BooleanField(default=False, help_text='Designates whether the user has verified their phone number.', verbose_name='phone verified'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last activity'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_order_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last order date'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='loyalty_points',
            field=models.PositiveIntegerField(default=0, verbose_name='loyalty points'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='marketing_emails',
            field=models.BooleanField(default=True, help_text='User agrees to receive marketing emails.', verbose_name='marketing emails'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='newsletter_subscription',
            field=models.BooleanField(default=True, help_text='User has subscribed to newsletters.', verbose_name='newsletter subscription'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='phone verification code'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='phone verification sent at'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='phone verified at'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sms_notifications',
            field=models.BooleanField(default=False, help_text='User agrees to receive SMS notifications.', verbose_name='SMS notifications'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_orders',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='total orders'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='total spent'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that phone number already exists.'}, max_length=20, null=True, unique=True, verbose_name='phone number'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='users_custo_email_c80f75_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['username'], name='users_custo_usernam_a8ad03_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['phone'], name='users_custo_phone_ad7713_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['date_joined'], name='users_custo_date_jo_3d5338_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['last_order_date'], name='users_custo_last_or_9aa8da_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_active', 'is_email_verified'], name='users_custo_is_acti_446b23_idx'),
        ),
        migrations.AddField(
            model_name='loyaltypointshistory',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_points_earned', to='orders.order'),
        ),
        migrations.AddField(
            model_name='loyaltypointshistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_points_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loyaltypointshistory',
            index=models.Index(fields=['user', 'created_at'], name='users_loyal_user_id_f98834_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltypointshistory',
            index=models.Index(fields=['order', 'created_at'], name='users_loyal_order_i_132c52_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['user', 'created_at'], name='users_usera_user_id_113a56_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['activity_type', 'created_at'], name='users_usera_activit_573fdc_idx'),
        ),
        migrations.AddIndex(
            model_name='useraddress',
            index=models.Index(fields=['user', 'is_default_shipping'], name='users_usera_user_id_8de24f_idx'),
        ),
        migrations.AddIndex(
            model_name='useraddress',
            index=models.Index(fields=['user', 'is_default_billing'], name='users_usera_user_id_72f961_idx'),
        ),
        migrations.AddIndex(
            model_name='useraddress',
            index=models.Index(fields=['county', 'city'], name='users_usera_county_529fac_idx'),
        ),
        migrations.AddConstraint(
            model_name='useraddress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default_shipping', True)), fields=('user', 'is_default_shipping'), name='unique_default_shipping_per_user'),
        ),
        migrations.AddConstraint(
            model_name='useraddress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default_billing', True)), fields=('user', 'is_default_billing'), name='unique_default_billing_per_user'),
        ),
    ]
