# Generated by Django 6.0 on 2025-12-09 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='wishlist',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If True, others can view this wishlist'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='name',
            field=models.CharField(default='My Wishlist', help_text='Name of the wishlist (e.g., Birthday, Christmas)', max_length=100),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'name')},
        ),
    ]
