# Generated by Django 6.0 on 2025-12-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
